---
controller_user_accounts:
  - user: "colin"
    is_superuser: false
    password: "redhat"

controller_templates:
  - name: WINTEL - 4.0_vmware_test_connectivity
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: 00_WINTEL_VMWARE_INV
    project: 01_WINTEL_VMWARE_USECASES
    playbook: 4.0_vmware_test_connectivity.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: eprocess_ee_vmware_001
    credentials:
      - vcenter_dev_cred
    survey_enabled: false
    survey_spec: {}
    state: present

  - name: WINTEL - 4.2_vmware_delete_all_poweredoff_virtual_machines_from_inventory_or_disk
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: 00_WINTEL_VMWARE_INV
    project: 01_WINTEL_VMWARE_USECASES
    playbook: 4.2_vmware_delete_all_poweredoff_virtual_machines_from_inventory_or_disk.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: eprocess_ee_vmware_001
    credentials:
      - vcenter_dev_cred
    survey_enabled: false
    survey_spec: {}
    state: present

  - name: WINTEL - 4.3_add_new_disk_to_a_virtual_machine
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: 00_WINTEL_VMWARE_INV
    project: 01_WINTEL_VMWARE_USECASES
    playbook: 4.3_add_new_disk_to_a_virtual_machine.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: eprocess_ee_vmware_001
    credentials:
      - vcenter_dev_cred
    survey_enabled: true
    survey_spec: "{{ lookup( 'template', 'template_surveys/survey_4.3_add_new_disk_to_a_virtual_machine.yml') | from_yaml }}"
    state: present

  - name: WINTEL - 4.4_increase_disk_space_of_virtual_machine
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: 00_WINTEL_VMWARE_INV
    project: 01_WINTEL_VMWARE_USECASES
    playbook: 4.4_increase_disk_space_of_virtual_machine.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: eprocess_ee_vmware_001
    credentials:
      - vcenter_dev_cred
    survey_enabled: true
    survey_spec: "{{ lookup( 'template', 'template_surveys/survey_4.4_increase_disk_space_of_virtual_machine.yml') | from_yaml }}"
    state: present

  - name: WINTEL - 4.5_create_virtual_machine_from_a_template
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: 00_WINTEL_VMWARE_INV
    project: 01_WINTEL_VMWARE_USECASES
    playbook: 4.5_create_virtual_machine_from_a_template.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: eprocess_ee_vmware_001
    credentials:
      - vcenter_dev_cred
    survey_enabled: true
    survey_spec: "{{ lookup( 'template', 'template_surveys/survey_4.5_create_virtual_machine_from_a_template.yml') | from_yaml }}"
    state: present

  - name: WINTEL - 4.6_create_virtual_machine_clone
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: 00_WINTEL_VMWARE_INV
    project: 01_WINTEL_VMWARE_USECASES
    playbook: 4.6_create_virtual_machine_clone.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: eprocess_ee_vmware_001
    credentials:
      - vcenter_dev_cred
    survey_enabled: true
    survey_spec: "{{ lookup( 'template', 'template_surveys/survey_4.6_create_virtual_machine_clone.yml') | from_yaml }}"
    state: present

  - name: WINTEL - 4.7_restore_virtual_machine_from_a_snapshot
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: 00_WINTEL_VMWARE_INV
    project: 01_WINTEL_VMWARE_USECASES
    playbook: 4.7_restore_virtual_machine_from_a_snapshot.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: eprocess_ee_vmware_001
    credentials:
      - vcenter_dev_cred
    survey_enabled: true
    survey_spec: "{{ lookup( 'template', 'template_surveys/survey_4.7_restore_virtual_machine_from_a_snapshot.yml') | from_yaml }}"
    state: present

  - name: WINTEL - 4.8_create_snapshot_from_a_virtual_machine
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: 00_WINTEL_VMWARE_INV
    project: 01_WINTEL_VMWARE_USECASES
    playbook: 4.8_create_snapshot_from_a_virtual_machine.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: eprocess_ee_vmware_001
    credentials:
      - vcenter_dev_cred
    survey_enabled: true
    survey_spec: "{{ lookup( 'template', 'template_surveys/survey_4.8_create_snapshot_from_a_virtual_machine.yml') | from_yaml }}"
    state: present

  - name: 5.2_rhel_ping
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.2_rhel_ping.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present
  - name: 5.3_rhel_check_volumes_over_80%_disk_use
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.3_rhel_check_volumes_over_80%_disk_use.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present  
  - name: 5.4_rhel_install_and_restart_snmpd_service_on_on_rhel_servers
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.4_rhel_install_and_restart_snmpd_service_on_on_rhel_servers.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present  
  - name: 5.5_rhel_install_and_restart_mdatp_on_all_rhel_servers
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.5_rhel_install_and_restart_mdatp_on_all_rhel_servers.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present  
  - name: 5.6_rhel_patch_rhel_servers_with_new_packages
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.6_rhel_patch_rhel_servers_with_new_packages.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present  
  - name: 5.7_reset_user_accounts_on_red_hat_identity_manager
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.7_reset_user_accounts_on_red_hat_identity_manager.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: true
    survey_spec: "{{ lookup( 'template', 'template_surveys/survey_5.7_reset_user_accounts_on_red_hat_identity_manager.yml') | from_yaml }}"
    state: present      
  - name: 5.8_rhel_create_nfs_share
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.8_rhel_create_nfs_share.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present  
  - name: 5.8_rhel_create_samba
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.8_rhel_create_samba.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present  
  - name: 5.9_rhel_java_installation_for_WebLogic_servers
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.9_rhel_java_installation_for_WebLogic_servers.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present              
  - name: 5.11_obdx_clearing_old_logs_in_odbx_log_domain_server_logs
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.11_obdx_clearing_old_logs_in_odbx_log_domain_server_logs.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present  
  - name: 5.12_flexcubes_weblogic_logs_management_and_archiving
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.12_flexcubes_weblogic_logs_management_and_archiving.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present      
  - name: 5.13_clear_fleod_reports_for_space_checks
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.13_clear_fleod_reports_for_space_checks.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present    
  - name: 5.14_clear_flexcubes_fron_end_application_logs
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.14_clear_flexcubes_fron_end_application_logs.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present  
  - name: 5.15_clear_flexcubes_backend_application_logs
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.15_clear_flexcubes_backend_application_logs.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present  
  - name: 5.16_clear_flexcubes_upload_progress_logs
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.16_clear_flexcubes_upload_progress_logs.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present  
  - name: 5.17_manage_weblogic_server_logs_for_mfa
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.17_manage_weblogic_server_logs_for_mfa.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present  
  - name: 5.19_archiving_of_weblogic_logs
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.19_archiving_of_weblogic_logs.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present  
  - name: 5.20_archiving_of_webserver_access_and_error_logs
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 5.20_archiving_of_webserver_access_and_error_logs.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: false
    survey_spec: {}
    state: present    
  - name: 8.1_swig_restart_and_switch_ucp_gateways
    description: Ansible Managed
    organization: Default
    job_type: run
    inventory: rhel_dev_inv
    project: 00_UNIX_RHEL_USECASES
    playbook: 8.1_swig_restart_and_switch_ucp_gateways.yml
    become_enabled: false
    instance_groups:
      - default
    verbosity: 3
    execution_environment: Default execution environment
    credentials:
      - rhel_dev_inv_cred
    survey_enabled: true
    survey_spec: "{{ lookup( 'template', 'template_surveys/survey_8.1_swig_restart_and_switch_ucp_gateways.yml') | from_yaml }}"
    state: present

    